package piglatin;

/**
 * Choose level (easy, medium, hard) that players want to play by click
 * button for each level and also have button for back to main game menu.
 * 
 * @author Kunyaruk Katebunlu
 */
public class Level extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ezBtn = new javax.swing.JButton();
        medBtn = new javax.swing.JButton();
        hrdBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        lvBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Level");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        ezBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/EZB.png"))); // NOI18N
        ezBtn.setBorderPainted(false);
        ezBtn.setContentAreaFilled(false);
        ezBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ezBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ezBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ezBtn);
        ezBtn.setBounds(50, 290, 140, 70);

        medBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/MedB.png"))); // NOI18N
        medBtn.setBorderPainted(false);
        medBtn.setContentAreaFilled(false);
        medBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medBtnActionPerformed(evt);
            }
        });
        getContentPane().add(medBtn);
        medBtn.setBounds(230, 290, 140, 70);

        hrdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/HardB.png"))); // NOI18N
        hrdBtn.setBorderPainted(false);
        hrdBtn.setContentAreaFilled(false);
        hrdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hrdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hrdBtn);
        hrdBtn.setBounds(410, 290, 140, 70);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Back.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(20, 420, 100, 70);

        lvBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Level.png"))); // NOI18N
        getContentPane().add(lvBG);
        lvBG.setBounds(0, 0, 600, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Open main game frame and close this frame when click button.
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new PlayerName().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * Go to easy level game frame and close this frame when click button.
     */
    private void ezBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ezBtnActionPerformed
        new QA_Easy().setVisible(true);
        dispose();
    }//GEN-LAST:event_ezBtnActionPerformed

    /**
     * Go to medium level game frame and close this frame when click button.
     */
    private void medBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medBtnActionPerformed
        new QA_Medium().setVisible(true);
        dispose();
    }//GEN-LAST:event_medBtnActionPerformed

    /**
     * Go to hard level game frame and close this frame when click button.
     */
    private void hrdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrdBtnActionPerformed
        new QA_Hard().setVisible(true);
        dispose();
    }//GEN-LAST:event_hrdBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton ezBtn;
    private javax.swing.JButton hrdBtn;
    private javax.swing.JLabel lvBG;
    private javax.swing.JButton medBtn;
    // End of variables declaration//GEN-END:variables
}
