package piglatin;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static piglatin.QA_Easy.score;

/**
 *
 * @author nxxkxxk
 */
public class QA_Hard extends javax.swing.JFrame {

    static int clicked = 0;
    static private String[] qHd;
    static private String[] qH = new String[5];
    static private String[] ans = new String[5];
    static String inAns;
    static int score = 0;
    static boolean check;

    /**
     * Creates new form Hard_No1
     */
    public QA_Hard() {
        initComponents();
        Question.setQHard();
        qHd = Question.getQHard();
        qSplit(qHd);
        qHard.setText(qH[clicked]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qHard = new javax.swing.JLabel();
        hardAns = new javax.swing.JTextField();
        nxtBtn = new javax.swing.JButton();
        hrdBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hard Mode");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        qHard.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        qHard.setForeground(new java.awt.Color(51, 0, 0));
        qHard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qHard.setText("Phrase / Sentence");
        getContentPane().add(qHard);
        qHard.setBounds(30, 70, 540, 80);

        hardAns.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        hardAns.setForeground(new java.awt.Color(51, 0, 0));
        hardAns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hardAns.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(hardAns);
        hardAns.setBounds(40, 306, 520, 80);

        nxtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Next.png"))); // NOI18N
        nxtBtn.setBorderPainted(false);
        nxtBtn.setContentAreaFilled(false);
        nxtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nxtBtn);
        nxtBtn.setBounds(480, 420, 100, 60);

        hrdBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Hard.png"))); // NOI18N
        getContentPane().add(hrdBG);
        hrdBG.setBounds(0, 0, 600, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setQandCheckAnsHard() {
        qHard.setText(qH[clicked]);
        inAns = hardAns.getText();
        check = CheckAndCount.checkA(ans[clicked], inAns);
        score = CheckAndCount.scoreHard(check, score);
    }

    private void nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtBtnActionPerformed
        clicked++;
        inAns = hardAns.getText();
        check = CheckAndCount.checkA(ans[clicked - 1], inAns);
        score = CheckAndCount.scoreHard(check, score);
        hardAns.setText("");
        switch (clicked) {
            case 1:
                setQandCheckAnsHard();
                break;
            case 2:
                setQandCheckAnsHard();
                break;
            case 3:
                setQandCheckAnsHard();
                break;
            case 4:
                setQandCheckAnsHard();
                break;
            default:
                clicked = 0;
                  String scoreTotal = Integer.toString(score);
                String txt = ScoreTable.recordScore(PlayerName.playerN, scoreTotal);
        {
            try {
                ScoreTable.writeToFileHard(txt);
            } catch (IOException ex) {
                Logger.getLogger(QA_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        {
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(QA_Hard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                new ScoreTable_Hard().setVisible(true);
                dispose();
        }
    }//GEN-LAST:event_nxtBtnActionPerformed

    static private void qSplit(String[] qHd) {
        for (int i = 0; i < qHd.length; i++) {
            String[] array = qHd[i].trim().split("; ");
            qH[i] = array[0];
            ans[i] = array[1];
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QA_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QA_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QA_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QA_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QA_Hard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hardAns;
    private javax.swing.JLabel hrdBG;
    private javax.swing.JButton nxtBtn;
    private javax.swing.JLabel qHard;
    // End of variables declaration//GEN-END:variables
}
