package piglatin;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static piglatin.QA_Easy.score;

/**
 *
 * @author nxxkxxk
 */
public class QA_Medium extends javax.swing.JFrame {

    static int clicked = 0;
    static private String[] qMd;
    static private String[] qM = new String[10];
    static private String[] ans = new String[10];
    static String inAns;
    static int score = 0;
    static boolean check;

    /**
     * Creates new form Medium_QA
     */
    public QA_Medium() {
        initComponents();
        Question.setQMedium();
        qMd = Question.getQMedium();
        qSplit(qMd);
        qMed.setText(qM[clicked]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medAns = new javax.swing.JTextField();
        nxtBtn = new javax.swing.JButton();
        qMed = new javax.swing.JLabel();
        medBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medium Mode");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        medAns.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        medAns.setForeground(new java.awt.Color(51, 0, 0));
        medAns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medAns.setToolTipText("");
        medAns.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(medAns);
        medAns.setBounds(80, 326, 290, 60);

        nxtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Next.png"))); // NOI18N
        nxtBtn.setBorderPainted(false);
        nxtBtn.setContentAreaFilled(false);
        nxtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nxtBtn);
        nxtBtn.setBounds(470, 409, 123, 60);

        qMed.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        qMed.setForeground(new java.awt.Color(51, 0, 0));
        qMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qMed.setText("word");
        getContentPane().add(qMed);
        qMed.setBounds(185, 76, 230, 70);

        medBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Medium.png"))); // NOI18N
        getContentPane().add(medBG);
        medBG.setBounds(0, 0, 600, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setQandCheckAnsMedium() {
        qMed.setText(qM[clicked]);
        inAns = medAns.getText();
        check = CheckAndCount.checkA(ans[clicked], inAns);
        score = CheckAndCount.scoreMedium(check, score);
    }

    private void nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtBtnActionPerformed
        clicked++;
        inAns = medAns.getText();
        check = CheckAndCount.checkA(ans[clicked - 1], inAns);
        score = CheckAndCount.scoreMedium(check, score);
        medAns.setText("");
        switch (clicked) {
            case 1:
                setQandCheckAnsMedium();
                break;
            case 2:
                setQandCheckAnsMedium();
                break;
            case 3:
                setQandCheckAnsMedium();
                break;
            case 4:
                setQandCheckAnsMedium();
                break;
            case 5:
                setQandCheckAnsMedium();
                break;
            case 6:
                setQandCheckAnsMedium();
                break;
            case 7:
                setQandCheckAnsMedium();
                break;
            case 8:
                setQandCheckAnsMedium();
                break;
            case 9:
                setQandCheckAnsMedium();
                break;
            default:
                clicked = 0;
                  String scoreTotal = Integer.toString(score);
                String txt = ScoreTable.recordScore(PlayerName.playerN, scoreTotal);
        {
            try {
                ScoreTable.writeToFileMedium(txt);
            } catch (IOException ex) {
                Logger.getLogger(QA_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        {
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(QA_Medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                new ScoreTable_Medium().setVisible(true);
                dispose();
        }
    }//GEN-LAST:event_nxtBtnActionPerformed

    static private void qSplit(String[] qMd) {
        for (int i = 0; i < qMd.length; i++) {
            String[] array = qMd[i].trim().split("; ");
            qM[i] = array[0];
            ans[i] = array[1];
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QA_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QA_Medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField medAns;
    private javax.swing.JLabel medBG;
    private javax.swing.JButton nxtBtn;
    private javax.swing.JLabel qMed;
    // End of variables declaration//GEN-END:variables
}
