/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piglatin;

/**
 *
 * @author nxxkxxk
 */
public class ScoreTable_Hard extends javax.swing.JFrame {
    private String[] topScore;
    private int[] scorePlayer = new int[0];
    private String[] namePlayer = new String[0];
    /**
     * Creates new form ScoreTable
     */
    public ScoreTable_Hard() {
        initComponents();
        ScoreTable.initHard();
        topScore = ScoreTable.getHardScore();
        scorePlayer = new int[topScore.length];
        namePlayer = new String[topScore.length];
        scoreSplit(topScore);
        sortScore();
        nameP1.setText(namePlayer[0]);
        nameP2.setText(namePlayer[1]);
        nameP3.setText(namePlayer[2]);
        nameP4.setText(namePlayer[3]);
        nameP5.setText(namePlayer[4]);
        String score1 = Integer.toString(scorePlayer[0]);
        scoreP1.setText(score1);
        String score2 = Integer.toString(scorePlayer[1]);
        scoreP2.setText(score2);
        String score3 = Integer.toString(scorePlayer[2]);
        scoreP3.setText(score3);
        String score4 = Integer.toString(scorePlayer[3]);
        scoreP4.setText(score4);
        String score5 = Integer.toString(scorePlayer[4]);
        scoreP5.setText(score5);
        QA_Hard.score = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameP1 = new javax.swing.JLabel();
        nameP2 = new javax.swing.JLabel();
        nameP3 = new javax.swing.JLabel();
        nameP4 = new javax.swing.JLabel();
        nameP5 = new javax.swing.JLabel();
        scoreP1 = new javax.swing.JLabel();
        scoreP2 = new javax.swing.JLabel();
        scoreP3 = new javax.swing.JLabel();
        scoreP4 = new javax.swing.JLabel();
        scoreP5 = new javax.swing.JLabel();
        restartBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        newGBtn = new javax.swing.JButton();
        scBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Score Table [Hard Lv.]");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        nameP1.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nameP1.setForeground(new java.awt.Color(102, 51, 0));
        nameP1.setText("PlayerName1");
        getContentPane().add(nameP1);
        nameP1.setBounds(150, 170, 260, 40);

        nameP2.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nameP2.setForeground(new java.awt.Color(102, 51, 0));
        nameP2.setText("PlayerName2");
        getContentPane().add(nameP2);
        nameP2.setBounds(150, 210, 260, 40);

        nameP3.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nameP3.setForeground(new java.awt.Color(102, 51, 0));
        nameP3.setText("PlayerName3");
        getContentPane().add(nameP3);
        nameP3.setBounds(150, 260, 260, 40);

        nameP4.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nameP4.setForeground(new java.awt.Color(102, 51, 0));
        nameP4.setText("PlayerName4");
        getContentPane().add(nameP4);
        nameP4.setBounds(150, 300, 260, 40);

        nameP5.setFont(new java.awt.Font("Marker Felt", 0, 36)); // NOI18N
        nameP5.setForeground(new java.awt.Color(102, 51, 0));
        nameP5.setText("PlayerName5");
        getContentPane().add(nameP5);
        nameP5.setBounds(150, 350, 260, 40);

        scoreP1.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        scoreP1.setForeground(new java.awt.Color(102, 51, 0));
        scoreP1.setText("XXXXX");
        getContentPane().add(scoreP1);
        scoreP1.setBounds(450, 170, 90, 40);

        scoreP2.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        scoreP2.setForeground(new java.awt.Color(102, 51, 0));
        scoreP2.setText("XXXXX");
        getContentPane().add(scoreP2);
        scoreP2.setBounds(450, 210, 90, 40);

        scoreP3.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        scoreP3.setForeground(new java.awt.Color(102, 51, 0));
        scoreP3.setText("XXXXX");
        getContentPane().add(scoreP3);
        scoreP3.setBounds(450, 260, 90, 40);

        scoreP4.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        scoreP4.setForeground(new java.awt.Color(102, 51, 0));
        scoreP4.setText("XXXXX");
        getContentPane().add(scoreP4);
        scoreP4.setBounds(450, 300, 90, 40);

        scoreP5.setFont(new java.awt.Font("Marker Felt", 0, 30)); // NOI18N
        scoreP5.setForeground(new java.awt.Color(102, 51, 0));
        scoreP5.setText("XXXXX");
        getContentPane().add(scoreP5);
        scoreP5.setBounds(450, 350, 90, 40);

        restartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/Restart.png"))); // NOI18N
        restartBtn.setBorderPainted(false);
        restartBtn.setContentAreaFilled(false);
        restartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(restartBtn);
        restartBtn.setBounds(40, 420, 167, 70);

        mainBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/MainB.png"))); // NOI18N
        mainBtn.setBorderPainted(false);
        mainBtn.setContentAreaFilled(false);
        mainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn);
        mainBtn.setBounds(230, 420, 167, 70);

        newGBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/NewGame.png"))); // NOI18N
        newGBtn.setBorderPainted(false);
        newGBtn.setContentAreaFilled(false);
        newGBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newGBtn);
        newGBtn.setBounds(410, 420, 150, 70);

        scBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectSource/SCTabH.png"))); // NOI18N
        getContentPane().add(scBG);
        scBG.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void scoreSplit(String[] topScore) {
        int[] clone = new int[topScore.length];
        for (int i = 0; i < topScore.length; i++) {
            String[] array = topScore[i].trim().split("; ");
            namePlayer[i] = array[0];
            clone[i] = Integer.parseInt(array[1]);
            scorePlayer[i] = clone[i];
        }
    }

    public void sortScore() {
        int maxScore1 = 0, maxScore2 = 0, maxScore3 = 0, maxScore4 = 0, maxScore5 = 0;
        int save = 0;
        for (int i = 0; i < scorePlayer.length; i++) {
            maxScore1 = Math.max(maxScore1, scorePlayer[i]);
            if (scorePlayer[i] == maxScore1) {
                save = i;
            }
        }
        if (scorePlayer[save] == maxScore1) {
            int saveScore = scorePlayer[0];
            scorePlayer[0] = scorePlayer[save];
            scorePlayer[save] = saveScore;
            String saveName = namePlayer[0];
            namePlayer[0] = namePlayer[save];
            namePlayer[save] = saveName;
        }
        for (int i = 1; i < scorePlayer.length; i++) {
            maxScore2 = Math.max(maxScore2, scorePlayer[i]);
            if (scorePlayer[i] == maxScore2) {
                save = i;
            }
        }
        if (scorePlayer[save] == maxScore2) {
            int saveScore = scorePlayer[1];
            scorePlayer[1] = scorePlayer[save];
            scorePlayer[save] = saveScore;
            String saveName = namePlayer[1];
            namePlayer[1] = namePlayer[save];
            namePlayer[save] = saveName;
        }
        for (int i = 2; i < scorePlayer.length; i++) {
            maxScore3 = Math.max(maxScore3, scorePlayer[i]);
            if (scorePlayer[i] == maxScore3) {
                save = i;
            }
        }
        if (scorePlayer[save] == maxScore3) {
            int saveScore = scorePlayer[2];
            scorePlayer[2] = scorePlayer[save];
            scorePlayer[save] = saveScore;
            String saveName = namePlayer[2];
            namePlayer[2] = namePlayer[save];
            namePlayer[save] = saveName;
        }
        for (int i = 3; i < scorePlayer.length; i++) {
            maxScore4 = Math.max(maxScore4, scorePlayer[i]);
            if (scorePlayer[i] == maxScore4) {
                save = i;
            }
        }
        if (scorePlayer[save] == maxScore4) {
            int saveScore = scorePlayer[3];
            scorePlayer[3] = scorePlayer[save];
            scorePlayer[save] = saveScore;
            String saveName = namePlayer[3];
            namePlayer[3] = namePlayer[save];
            namePlayer[save] = saveName;
        }
        for (int i = 4; i < scorePlayer.length; i++) {
            maxScore5 = Math.max(maxScore5, scorePlayer[i]);
            if (scorePlayer[i] == maxScore5) {
                save = i;
            }
        }
        if (scorePlayer[save] == maxScore5) {
            int saveScore = scorePlayer[4];
            scorePlayer[4] = scorePlayer[save];
            scorePlayer[save] = saveScore;
            String saveName = namePlayer[4];
            namePlayer[4] = namePlayer[save];
            namePlayer[save] = saveName;
        }
       

    }
    
    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        new PlayerName().setVisible(true);
        dispose();
    }//GEN-LAST:event_newBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        new MainGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        //TODO put code to reset the score of this player in this level to be 0
        new QA_Hard().setVisible(true);
        dispose();
    }//GEN-LAST:event_restartBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreTable_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreTable_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreTable_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreTable_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreTable_Hard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainBtn;
    private javax.swing.JLabel nameP1;
    private javax.swing.JLabel nameP2;
    private javax.swing.JLabel nameP3;
    private javax.swing.JLabel nameP4;
    private javax.swing.JLabel nameP5;
    private javax.swing.JButton newGBtn;
    private javax.swing.JButton restartBtn;
    private javax.swing.JLabel scBG;
    private javax.swing.JLabel scoreP1;
    private javax.swing.JLabel scoreP2;
    private javax.swing.JLabel scoreP3;
    private javax.swing.JLabel scoreP4;
    private javax.swing.JLabel scoreP5;
    // End of variables declaration//GEN-END:variables
}
